name: Deploy to Firebase Hosting on merge to main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Node.js (version LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou version que tu utilises localement

      # 3. Installer les dépendances et builder dans le dossier frontend
      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # 4. Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COCMARKET_0 }}"
          projectId: "cocmarket-0"
          channelId: "live"  # ou "live" pour déploiement production
          # Répertoire à déployer (le dossier "build" de Vite)
          # Par défaut, Vite génère dans "dist"
          # Firebase Hosting doit déployer le contenu de "frontend/dist"
          # Donc on indique ici le chemin relatif à la racine du repo
          hostingTarget: "frontend/dist"
